### ISSUE TITLE
404 on /oidc/ui

### ISSUE THREAD

**Issue by DrOfAwesomeness** [data-platform-hq/mlflow-oidc-auth#33]
Hi there! I'm running into an issue where I can log in with OpenID Connect after deploying the plugin, but when I try to edit permissions (or get otherwise redirected to /oidc/ui), I get a 404 page.

I'm running MLFlow in Docker. I installed the plugin by including it in the pip install line in my Dockerfile:
```dockerfile
FROM python:3.12
RUN groupadd --gid 1001 mlflow && \
  useradd --uid 1001 --gid mlflow --shell /bin/bash mlflow && \
  pip install psycopg2 boto3 mlflow-oidc-auth==2.0.0
RUN mkdir /work && chown mlflow:mlflow /work
USER mlflow
WORKDIR /work
CMD ["bash"]
```

And I set the environment variables described in the README in my docker-compose file:
```yaml
services:
  db:
    image: postgres:16.4
    restart: always
    shm_size: 128mb
    environment:
      POSTGRES_USER: mlflow
      POSTGRES_PASSWORD: <snip>
      POSTGRES_DB: mlflow
    volumes:
      - mlflow_dbdata:/var/lib/postgresql/data
    networks:
      - mlflow_net
  mlflow:
    build:
      context: .
      dockerfile: Dockerfile.mlflow
    environment:
      OIDC_DISCOVERY_URL: <snip>
      OIDC_CLIENT_ID: <snip>
      OIDC_CLIENT_SECRET: <snip>
      OIDC_PROVIDER_DISPLAY_NAME: <snip>
      OIDC_USERS_DB_URI: <snip>
      OIDC_GROUP_NAME: "/MLFlow Users"
      OIDC_ADMIN_GROUP_NAME: "/MLFlow Admins"
      MLFLOW_S3_ENDPOINT_URL: <snip>
      AWS_ACCESS_KEY_ID: <snip>
      AWS_SECRET_ACCESS_KEY: <snip>
      OIDC_REDIRECT_URI: https://<snip>/callback
      OAUTHLIB_INSECURE_TRANSPORT: true # https is offloaded by cloudflared
      SECRET_KEY: <snip>
    networks:
      - mlflow_net
    ports:
      - 8080:8080
    command: ["mlflow", "server", "--app-name", "oidc-auth", "--backend-store-uri", "<snip>", "--artifacts-destination", "s3://<snip>", "--host", "0.0.0.0", "--port", "8080"]
networks:
  mlflow_net:
volumes:
  mlflow_dbdata:
```

If it's relevent, I'm running behind a Cloudflare tunnel, so Cloudflare is terminating TLS for me (which is why I have `OAUTHLIB_INSECURE_TRANSPORT` set).

When I go to my MLFlow URL, I see the login page, and I'm able to go through the login flow. When I am redirected back to MLFlow, it redirects me to /oidc/ui, which gives a 404. If I manually go to the root URL afterwords, I see my name in the top right corner, so it is successfully logging me in.

This is my first time rolling out MLFlow, so it's entirely possible I'm making a really obvious mistake - sorry if that's the case here!
